name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: get solc binary
      run: |
        sudo apt-get install -y wget && \
        sudo wget -c https://raw.githubusercontent.com/ethereum/solc-bin/gh-pages/linux-amd64/solc-linux-amd64-v0.8.7%2Bcommit.e28d00a7 -O /usr/local/bin/solc && \
        sudo chmod +x /usr/local/bin/solc
        solc --version

    - name: Format
      run: bash ./scripts/github-action.gofmt.sh

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

/home/runner/go/bin
/opt/hostedtoolcache/go/1.15.15/x64/bin
/home/linuxbrew/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/sbin
/home/runner/.local/bin
/opt/pipx_bin
/usr/share/rust/.cargo/bin
/home/runner/.config/composer/vendor/bin
/usr/local/.ghcup/bin
/home/runner/.dotnet/tools
/snap/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/snap/bin
