name: Go

# new tag event
on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: command
      run: bash ./.gha.precheck.sh

    - name: command
      run: bash ./.gha.package.sh

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Change Log
          - Lorem ipsum dolor sit amet, consectetur adipiscing elit
        draft: false
        prerelease: false

    - name: Release with attachment
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ontology-rollup-linux.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # build-macos:
  #   # after build ok, we patch macos version binary
  #   needs: build
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Set up Go
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: 1.13

  #   - name: command
  #     run: bash ./.gha.deploy.bash

  #   - name: Release with attachment
  #     uses: softprops/action-gh-release@v1
  #     if: startsWith(github.ref, 'refs/tags/')
  #     with:
  #       files: |
  #         ontology-darwin-amd64
  #         tool-darwin.zip
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
